image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Logging into the GitLab Container Registry..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "Building the Docker image..."
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - echo "Pushing the Docker image..."
    - docker push $CI_REGISTRY_IMAGE:latest

test:
  stage: test
  script:
    - echo "Pulling the Docker image..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest
    - echo "Testing the Docker image..."
    - docker run --rm $CI_REGISTRY_IMAGE python -c "print('Tests Passed')"

deploy:
  stage: deploy
  image: docker:latest
  services:
    - name: docker
      alias: docker
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_CONFIG: "/builds/.docker"
  script:
    - echo "Deploying the Docker image locally..."
    # Log in to GitLab Container Registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    # Pull the latest image from GitLab Container Registry
    - docker pull $CI_REGISTRY_IMAGE:latest
    # Stop and remove any running container with the same name
    - docker stop devops-ml-app || true
    - docker rm devops-ml-app || true
    # Run the container with the the pulled image
    - docker run -d -p 5000:5000 --name devops-ml-app $CI_REGISTRY_IMAGE:latest
  tags:
    - local

